In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
from keras.models import Sequential
from keras.layers import Dense
from keras.datasets import mnist


In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()


In [3]:
X_train = X_train.reshape(X_train.shape[0], -1)
X_test = X_test.reshape(X_test.shape[0], -1)
X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0


In [4]:
smote = SMOTE()
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

model = Sequential()
model.add(Dense(128, activation='relu', input_shape=(X_train_resampled.shape[1],)))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train_resampled, y_train_resampled, epochs=50, batch_size=32, validation_data=(X_test, y_test))

y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/50
2107/2107 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.8829 - loss: 0.4034 - val_accuracy: 0.9641 - val_loss: 0.1179
Epoch 2/50
2107/2107 ━━━━━━━━━━━━━━━━━━━━ 18s 4ms/step - accuracy: 0.9720 - loss: 0.0953 - val_accuracy: 0.9743 - val_loss: 0.0807
Epoch 3/50
2107/2107 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9816 - loss: 0.0606 - val_accuracy: 0.9768 - val_loss: 0.0749
Epoch 4/50
2107/2107 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9853 - loss: 0.0455 - val_accuracy: 0.9760 - val_loss: 0.0792
Epoch 5/50
2107/2107 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9883 - loss: 0.0359 - val_accuracy: 0.9776 - val_loss: 0.0759
Epoch 6/50
2107/2107 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9910 - loss: 0.0266 - val_accuracy: 0.9769 - val_loss: 0.0815
Epoch 7/50
2107/2107 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9931 - loss: 0.0210 - val_accuracy: 0.9762 - val_loss: 0.0851
Epoch 8/50
2107/2107 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9943 - loss: 0.0

In [5]:
accuracy = accuracy_score(y_test, y_pred_classes)
print("Accuracy:", accuracy)

print(classification_report(y_test, y_pred_classes))
print(confusion_matrix(y_test, y_pred_classes))

Accuracy: 0.9786
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.97      0.97      1032
           3       0.99      0.98      0.98      1010
           4       0.98      0.97      0.97       982
           5       0.97      0.98      0.98       892
           6       0.98      0.98      0.98       958
           7       0.99      0.97      0.98      1028
           8       0.96      0.98      0.97       974
           9       0.97      0.97      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000

[[ 970    1    0    0    0    1    3    2    2    1]
 [   0 1123    3    0    0    0    1    2    6    0]
 [   6    0 1002    3    4    0    4    3   10    0]
 [   2    0    6  990    0    5    0    0    4    3]
 [   0    0 

0.9786
